version: 0.2

env:
  variables:
    DB_ROOT_PASSWORD: "password"
    DB_HOST: "localhost"
    DB_PASSWORD: "password"
    DB_SOCKET: "/var/run/mysqld/mysqld.sock"
    KEYID: "5072E1F5"

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install supervisor
  build:
    commands:
      - echo "Running all unit tests"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
