#!/bin/bash
sudo apt-get update
sudo apt-get install -y python3 python-dev python3-pip supervisor
pip install virtualenv
cd /home/ec2-user/python-flask-service
virtualenv environment
source environment/bin/activate
pip install -r requirements.txt
pip install supervisor
